name: Run Mailer Service Tests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run Tests for Mailer Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        run: |
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Navigate to mailer-service folder
        run: cd mailer-service

      - name: Install mailer-service dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
