name: Run Mailer Service Tests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run Tests for Mailer Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Run Jest tests
        working-directory: ./mailer-service
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REGION_KEY: ${{ secrets.REGION_KEY }}
          MAIL_KEY: ${{ secrets.MAIL_KEY }}
        run: |
          npm install
          npm test
