name: Versioning Manager

on:
  push:
    branches:
      - main

jobs:
  tag_manager:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git status
          git branch -q

      - name: Check repository
        run: |
          ls && pwd
